"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from environ import Env


env = Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.str('DEBUG')
# DEBUG = False

ALLOWED_HOSTS = env.str('ALLOWED_HOSTS').split(',')
# ALLOWED_HOSTS = ['0.0.0.0', 'localhost', '127.0.0.1', 'my.domain.com']


# Application definition

INSTALLED_APPS = [
    # default system apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd-party
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'drf_spectacular',
    'rest_framework_simplejwt.token_blacklist',

    # local
    # 'test_app',
    # 'test_app.apps.TestAppConfig',
    'library.apps.LibraryConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'library.middlewares.JWTAuthMiddleware',  # NEW
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'library.middlewares.TestRequestNotificationMiddleware',
]

ROOT_URLCONF = 'config.urls'

# AUTH_USER_MODEL = '<app label>.<model name>'
# AUTH_USER_MODEL = 'django.contrib.auth.User'
# тут мы указываем DJango какую именно модель из какого приложения мы берём для работы с пользователями
# по дефолту Django как раз работает со своим пользователем, нам это не подходит
AUTH_USER_MODEL = 'library.User'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if env.bool('USE_REMOTE'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': env.str('MYSQL_NAME'),
            'USER': env.str('MYSQL_USER'),
            'PASSWORD': env.str('MYSQL_PASSWORD'),
            'HOST': env.str('MYSQL_HOST'),
            'PORT': env.int('MYSQL_PORT'),
        },
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        },

        # 'secondary': {
        #     ...
        # }
    }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'my_database',
#         'USER': 'test_user',
#         'PASSWORD': 'super_strong_password123',
#         'HOST': '127.0.0.1',
#         'PORT': 3306,
#     },
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    # {
    #     'NAME': ''
    # }
]  # qwe


REST_FRAMEWORK = {
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'DEFAULT_PAGINATION_CLASS': 'paginators.CustomCursorPaginator',
    # 'PAGE_SIZE': 5
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.BasicAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated'
    ],
}

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=3), # время жизни токена доступа (с ним делаем запросы)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7), # время жизни токена обновления (с ним делаем запросы)

    # Ротация(обновление и перевыпуск) токенов при обновлении \ истечении срока жизни
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True, # если включаем ротацию и чёрный список -- допом регистрируем +1 приложение и делаем миграции для создания таблиц чёрного списка
    "BLACKLIST_ENABLED": True, # если поставить True == нужна миграция
    "JTI_CLAIM": "jti",

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}


SPECTACULAR_SETTINGS = {
    # Здесь мы задаём общее название всей API-документации.
    # Именно этот текст будет виден в верхней части Swagger и Redoc.
    # Это помогает сразу понять, к какому проекту относится документация.
    "TITLE": "Project API",

    # Здесь мы задаём краткое описание документации.
    # Обычно в этом поле пишут, для чего нужна документация и кто может ею пользоваться.
    # Это первое пояснение для разработчика перед началом работы с API.
    "DESCRIPTION": (
        "Внутренняя документация API. "
        "Доступ к schema/UI только для staff пользователей."
    ),

    # Здесь мы указываем версию API.
    # Это полезно, чтобы разработчик сразу видел, с какой версией проекта он сейчас работает.
    # Особенно это важно, если API со временем развивается и меняется.
    "VERSION": "1.0.0",

    # Здесь мы указываем версию OpenAPI-формата, в котором будет строиться схема.
    # Swagger и Redoc читают именно OpenAPI-схему.
    # Эта настройка помогает явно зафиксировать нужный формат генерации документации.
    "OAS_VERSION": "3.0.3",

    # Здесь мы указываем, нужно ли включать endpoint схемы в саму же схему.
    # Обычно это не нужно, потому что маршрут документации редко имеет смысл показывать внутри самой документации.
    # Поэтому чаще всего эту настройку отключают.
    "SERVE_INCLUDE_SCHEMA": False,

    # Здесь мы указываем, должна ли документация считаться публичной.
    # Если поставить False, схема будет строиться с учётом прав текущего пользователя.
    # Это полезно, если разным пользователям нужно показывать разный набор endpoints.
    "SERVE_PUBLIC": False,

    # Здесь мы задаём permissions именно для страниц документации:
    # schema, swagger и redoc.
    # Это не permissions для всего API, а только для доступа к самой документации.
    "SERVE_PERMISSIONS": [
        # Здесь мы указываем, что открывать документацию могут только staff-пользователи.
        # В DRF IsAdminUser проверяет флаг is_staff.
        "rest_framework.permissions.IsAdminUser",
    ],

    # Здесь мы задаём аутентификацию именно для открытия Swagger/Redoc в браузере.
    # Это снова настройка не для всего API, а именно для самой страницы документации.
    "SERVE_AUTHENTICATION": [
        # Здесь мы используем обычную браузерную сессию Django.
        # Это удобно, потому что пользователь может сначала залогиниться через session,
        # а уже потом спокойно открыть Swagger в браузере.
        "rest_framework.authentication.SessionAuthentication",
    ],

    # Здесь мы указываем, какие способы авторизации нужно показывать уже внутри Swagger.
    # То есть это настройка не для открытия страницы, а для отправки запросов к самому API из Swagger UI.
    "AUTHENTICATION_WHITELIST": [
        # Здесь оставляем только JWT, чтобы Swagger показывал только нужный способ авторизации.
        # Это делает интерфейс чище и не путает разработчика лишними вариантами.
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],

    # Здесь мы настраиваем поведение самого интерфейса Swagger UI.
    "SWAGGER_UI_SETTINGS": {
        # Эта настройка позволяет делать прямые ссылки на конкретный раздел или endpoint внутри Swagger.
        # Это удобно, когда нужно быстро отправить кому-то ссылку сразу на нужный метод.
        "deepLinking": True,

        # Эта настройка показывает operationId — техническое имя операции в OpenAPI-схеме.
        # Обычно это полезно для генерации клиентов и для лучшего понимания внутренней структуры схемы.
        "displayOperationId": True,

        # Эта настройка сохраняет введённую авторизацию после обновления страницы.
        # Благодаря ей JWT-токен не придётся вставлять заново после каждого refresh.
        "persistAuthorization": True,

        # Эта настройка включает строку поиска по Swagger UI.
        # Если endpoints становится много, поиск сильно упрощает навигацию.
        "filter": True,

        # Эта настройка включает кнопку "Try it out".
        # Благодаря ей можно отправлять реальные запросы к API прямо из Swagger.
        "tryItOutEnabled": True,

        # Эта настройка задаёт способ раскрытия разделов документации при открытии страницы.
        # Значение "list" показывает всё в компактном формате списком.
        # Это помогает не перегружать интерфейс сразу при первом открытии.
        "docExpansion": "list",

        # Эта настройка отвечает за глубину раскрытия схем моделей.
        # Чем больше число, тем подробнее Swagger будет сразу раскрывать структуры данных.
        "defaultModelsExpandDepth": 2,

        # Эта настройка отвечает за глубину раскрытия конкретной модели внутри endpoint.
        # Это помогает балансировать между подробностью и читаемостью страницы.
        "defaultModelExpandDepth": 2,

        # Эта настройка показывает время выполнения запроса после его отправки из Swagger.
        # Это удобно при ручном тестировании и быстрой оценке ответа API.
        "displayRequestDuration": True,

        # Эта настройка сортирует теги по алфавиту.
        # Так документация выглядит аккуратнее и по ней проще перемещаться.
        "tagsSorter": "alpha",

        # Эта настройка сортирует операции по алфавиту.
        # Это делает порядок отображения более предсказуемым.
        "operationsSorter": "alpha",
    },

    # Здесь можно передать настройки для OAuth2 в Swagger UI.
    # Если OAuth2 в проекте не используется, достаточно оставить пустой словарь.
    "SWAGGER_UI_OAUTH2_CONFIG": {},

    # Здесь можно передать дополнительные настройки для Redoc.
    # Если специальных требований нет, можно оставить пустой словарь.
    "REDOC_UI_SETTINGS": {},

    # Здесь мы указываем общий префикс API-маршрутов.
    # Это помогает drf-spectacular лучше понимать структуру путей проекта.
    # Особенно полезно, если все endpoints лежат, например, под /api/v1/.
    "SCHEMA_PATH_PREFIX": r"/api/v[0-9]+",

    # Здесь мы указываем, что схемы request и response нужно разделять.
    # Это полезно, когда входящие и исходящие данные отличаются по структуре.
    # В результате документация становится точнее и понятнее.
    "COMPONENT_SPLIT_REQUEST": True,

    # Здесь мы включаем автоматическую сортировку операций в итоговой схеме.
    # Это помогает сделать документацию более стабильной и аккуратной.
    "SORT_OPERATIONS": True,

    # Здесь мы включаем автоматическую сортировку параметров внутри каждого endpoint.
    # Это делает отображение параметров более понятным и предсказуемым.
    "SORT_OPERATION_PARAMETERS": True,

    # Здесь мы задаём контактную информацию, которую можно показать в документации.
    # Это полезно, если нужно указать команду или человека, отвечающего за API.
    "CONTACT": {
        # Здесь указываем название команды или имя ответственного.
        "name": "Backend Team",

        # Здесь указываем email для связи по вопросам, связанным с API.
        "email": "backend@example.com",
    },
}


# LOGGING = {  # Главный словарь конфигурации logging для Django.
#     "version": 1,  # Версия формата dictConfig; для Python logging это стандартное обязательное поле.
#     "disable_existing_loggers": False,  # Не отключаем встроенные логгеры Django, чтобы не потерять стандартные логи.
#     "formatters": {  # Здесь описываем шаблоны, как будет выглядеть каждая строка лога.
#         "simple": {  # Имя форматтера; потом будем ссылаться на него из handlers.
#             "format": "[{levelname}] {asctime} {name}: {message}",  # Формат строки: уровень, время, имя логгера и сообщение.
#             "style": "{",  # Говорим logging, что шаблон написан в стиле str.format, а не через %.
#         },
#     },
#     "handlers": {  # Здесь описываем, куда физически отправлять лог-записи.
#         "console": {  # Handler с именем console для вывода логов в stdout/stderr терминала.
#             "class": "logging.StreamHandler",  # Стандартный handler Python для вывода в консоль.
#             "formatter": "simple",  # Говорим handler'у использовать форматтер simple.
#             "level": "INFO",  # Этот handler будет принимать только INFO и выше.
#         },
#     },
#     "loggers": {  # Здесь связываем конкретные логгеры с конкретными handlers.
#         "django": {  # Главный логгер Django и его дочерних пространств имён.
#             "handlers": ["console"],  # Все сообщения этого логгера отправляем в console.
#             "level": "INFO",  # Логгер будет пропускать INFO и выше.
#             "propagate": False,  # Не передаём сообщения выше по иерархии, чтобы не было дублей.
#         },
#         "library": {  # Наш собственный логгер для приложения myapp.
#             "handlers": ["console"],  # Логи приложения тоже отправляем в console.
#             "level": "DEBUG",  # Для своего приложения можно держать более подробный уровень.
#             "propagate": False,  # Также отключаем всплытие вверх, чтобы избежать повторов.
#         },
#     },
# }

# LOG_LEVEL = 'DEBUG' if DEBUG else 'INFO'      # ← переключаем через DEBUG
#
#
# import os  # Нужен для общих операций с ОС и путями.
# LOGS_DIR = BASE_DIR / "logs"  # Директория, где будут храниться лог-файлы.
# LOGS_DIR.mkdir(exist_ok=True)  # Создаём папку logs, если её ещё нет, чтобы FileHandler не упал.
#
# LOGGING = {  # Основная конфигурация logging.
#     "version": 1,  # Версия dictConfig.
#     "disable_existing_loggers": False,  # Сохраняем стандартные логгеры Django.
#     "formatters": {  # Блок шаблонов вывода логов.
#         "simple": {  # Форматтер для консоли.
#             "format": "[{levelname}] {asctime} {name}: {message}",  # Короткий человекочитаемый формат.
#             "style": "{",  # Используем {}-стиль форматирования.
#         },
#         "verbose": {  # Более подробный форматтер для файлов.
#             "format": "[{levelname}] {asctime} {name} | module={module} | process={process:d} | thread={thread:d} | {message}",  # Добавляем модуль, процесс, поток.
#             "style": "{",  # Также используем {}-стиль.
#         },
#     },
#     "handlers": {  # Блок обработчиков логов.
#         "console": {  # Вывод логов в терминал.
#             "class": "logging.StreamHandler",  # Консольный handler.
#             "formatter": "simple",  # Для консоли оставляем короткий формат.
#             "level": "INFO",  # В консоль пишем INFO и выше.
#         },
#         "file": {  # Handler для записи логов в файл.
#             "class": "logging.FileHandler",  # Стандартный файловый handler Python.
#             "filename": LOGS_DIR / "app.log",  # Путь до файла логов приложения.
#             "formatter": "verbose",  # Для файла используем более подробный формат.
#             "level": "DEBUG",  # В файл пишем даже DEBUG, чтобы потом глубже разбирать поведение.
#             "encoding": "utf-8",  # Чтобы кириллица и спецсимволы писались без мусора.
#         },
#     },
#     "loggers": {  # Описание логгеров.
#         "django": {  # Главный Django логгер.
#             "handlers": ["console", "file"],  # Пишем и в консоль, и в файл одновременно.
#             "level": "INFO",  # Для Django обычно достаточно INFO и выше.
#             "propagate": False,  # Убираем дальнейшее всплытие во избежание дублей.
#         },
#         "library": {  # Наш прикладной логгер.
#             "handlers": ["console", "file"],  # Логи приложения тоже в оба места.
#             "level": "DEBUG",  # Для своего кода держим DEBUG.
#             "propagate": False,  # Не пускаем записи выше.
#         },
#     },
# }





# Проблема FileHandler: файл растёт бесконечно.
# Поэтому следующий логический шаг — RotatingFileHandler.

# LOGS_DIR = BASE_DIR / "logs"  # Папка с логами.
# LOGS_DIR.mkdir(exist_ok=True)  # Гарантируем существование папки logs.
#
# LOGGING = {  # Основной словарь настройки логирования.
#     "version": 1,  # Версия dictConfig.
#     "disable_existing_loggers": False,  # Не вырубаем дефолтные логгеры Django.
#     "formatters": {  # Шаблоны для текстового вывода.
#         "simple": {  # Короткий формат для консоли.
#             "format": "[{levelname}] {asctime} {name}: {message}",  # Быстро читаемый шаблон для экрана.
#             "style": "{",  # Используем {}-формат.
#         },
#         "verbose": {  # Подробный формат для файлов.
#             "format": "[{levelname}] {asctime} {name} | module={module} | func={funcName} | "
#                       "line={lineno:d} | process={process:d} | thread={thread:d} | {message}",  # Добавляем функцию и номер строки.
#             "style": "{",  # Используем {}-стиль.
#         },
#     },
#     "handlers": {  # Куда отправлять записи логов.
#         "console": {  # Консольный handler.
#             "class": "logging.StreamHandler",  # Печать логов в терминал.
#             "formatter": "simple",  # Для экрана — простой формат.
#             "level": "INFO",  # В терминал — только INFO и выше.
#         },
#         "file": {  # Файловый handler с ротацией.
#             "class": "logging.handlers.RotatingFileHandler",  # Встроенный handler Python с ротацией по размеру файла.
#             "filename": LOGS_DIR / "app.log",  # Основной текущий лог-файл.
#             "maxBytes": 5 * 1024 * 1024,  # После 5 МБ файл будет ротирован.
#             "backupCount": 5,  # Храним 5 старых файлов app.log.1 ... app.log.5.
#             "formatter": "verbose",  # Пишем подробный формат, чтобы удобно расследовать проблемы.
#             "level": "DEBUG",  # В файл сохраняем даже DEBUG.
#             "encoding": "utf-8",  # Корректная запись Unicode.
#         },
#     },
#     "loggers": {  # Набор настроенных логгеров.
#         "django": {  # Логгер Django.
#             "handlers": ["console", "file"],  # И в терминал, и в файл.
#             "level": "INFO",  # Для системных событий Django обычно INFO достаточно.
#             "propagate": False,  # Избегаем дублей через корень.
#         },
#         "library": {  # Логгер нашего приложения.
#             "handlers": ["console", "file"],  # Также отправляем в оба handler'а.
#             "level": "DEBUG",  # Свой код логируем детальнее.
#             "propagate": False,  # Не даём записям дублироваться через родителей.
#         },
#     },
# }







# Разделяем логи по смыслу: app, errors, db
#
# Следующий логичный шаг: один файл на всё — уже неудобно.
#
# Поэтому:
    # общий лог приложения;
    # отдельный файл только под ошибки;
    # отдельный лог SQL-запросов.



# LOGS_DIR = BASE_DIR / "logs"  # Папка с логами.
# LOGS_DIR.mkdir(exist_ok=True)  # Гарантируем существование папки logs.
#
# LOGGING = {  # Корневая конфигурация logging.
#     "version": 1,  # Версия формата dictConfig.
#     "disable_existing_loggers": False,  # Не отключаем встроенные логгеры Django.
#     "formatters": {  # Описание форматтеров.
#         "simple": {  # Лаконичный форматтер.
#             "format": "[{levelname}] {asctime} {name}: {message}",  # Короткая форма для быстрого чтения.
#             "style": "{",  # Форматирование через {}.
#         },
#         "verbose": {  # Подробный форматтер.
#             "format": "[{levelname}] {asctime} {name} | module={module} | func={funcName} | line={lineno:d} | pid={process:d} | tid={thread:d} | {message}",  # Максимум полезного контекста на строку.
#             "style": "{",  # Форматирование через {}.
#         },
#         "sql": {  # Отдельный форматтер для SQL.
#             "format": "[{levelname}] {asctime} {name} | duration={duration} | sql={message}",  # Удобный формат именно для SQL-диагностики.
#             "style": "{",  # Используем {}-стиль.
#         },
#     },
#     "handlers": {  # Описание мест назначения логов.
#         "console": {  # Вывод в терминал.
#             "class": "logging.StreamHandler",  # Стандартный консольный handler.
#             "formatter": "simple",  # На экран выводим короткий формат.
#             "level": "INFO",  # В консоль отправляем только INFO и выше.
#         },
#         "app_file": {  # Общий файл приложения.
#             "class": "logging.handlers.RotatingFileHandler",  # Файловый handler с ротацией по размеру.
#             "filename": LOGS_DIR / "app.log",  # Основной лог приложения.
#             "maxBytes": 10 * 1024 * 1024,  # Ротация после 10 МБ.
#             "backupCount": 10,  # Держим 10 архивных файлов.
#             "formatter": "verbose",  # Пишем подробный формат.
#             "level": "DEBUG",  # Сохраняем все уровни начиная с DEBUG.
#             "encoding": "utf-8",  # Корректная кодировка файла.
#         },
#         "error_file": {  # Отдельный файл только для ошибок.
#             "class": "logging.handlers.RotatingFileHandler",  # Тоже используем ротацию.
#             "filename": LOGS_DIR / "errors.log",  # Файл ошибок.
#             "maxBytes": 10 * 1024 * 1024,  # Ротация после 10 МБ.
#             "backupCount": 10,  # Храним 10 старых файлов ошибок.
#             "formatter": "verbose",  # В ошибках нужен максимально полный контекст.
#             "level": "ERROR",  # Только ERROR и CRITICAL попадут в этот файл.
#             "encoding": "utf-8",  # Корректная кодировка.
#         },
#         "db_file": {  # Отдельный файл под SQL-логи.
#             "class": "logging.handlers.RotatingFileHandler",  # Ротация по размеру.
#             "filename": LOGS_DIR / "db.log",  # Файл для SQL-запросов.
#             "maxBytes": 20 * 1024 * 1024,  # SQL часто объёмный, поэтому лимит чуть выше.
#             "backupCount": 5,  # Храним 5 предыдущих файлов SQL.
#             "formatter": "sql",  # Специальный формат для SQL-записей.
#             "level": "DEBUG",  # SQL в Django логируется на DEBUG уровне.
#             "encoding": "utf-8",  # Корректная кодировка.
#         },
#     },
#     "loggers": {  # Связка логгеров с handler'ами.
#         "django": {  # Общие системные логи Django.
#             "handlers": ["console", "app_file", "error_file"],  # Обычные события — в app.log, ошибки — ещё и в errors.log.
#             "level": "INFO",  # Для Django держим INFO и выше.
#             "propagate": False,  # Без всплытия, чтобы не получить дубли.
#         },
#         "django.request": {  # Логи, связанные с HTTP-запросами и ошибками обработки запросов.
#             "handlers": ["console", "app_file", "error_file"],  # Ошибки запросов дублируем в отдельный error-файл.
#             "level": "WARNING",  # 4XX и 5XX здесь особенно интересны; WARNING — разумный порог.
#             "propagate": False,  # Не пускаем выше.
#         },
#         "django.db.backends": {  # Логгер SQL-запросов Django ORM.
#             "handlers": ["db_file"],  # SQL пишем только в отдельный db.log.
#             "level": "DEBUG" if DEBUG else "INFO",  # В debug-режиме собираем SQL детально, в prod обычно приглушаем.
#             "propagate": False,  # Не смешиваем SQL с общими логами.
#         },
#         "library": {  # Основной логгер нашего бизнес-кода.
#             "handlers": ["console", "app_file", "error_file"],  # Рабочие события — в app.log, ошибки — дополнительно в errors.log.
#             "level": "DEBUG",  # Своё приложение логируем подробно.
#             "propagate": False,  # Без дублей через родителей.
#         },
#     },
# }







# Теперь делаем следующий шаг:
#
# ротация по времени;
#     разделение debug/prod через фильтры;
#     email админам на критичные ошибки в DEBUG=False (больше как заглушка. Нужен прям настоящий SMPT сервер. Но это возможно в целом.)
#     отдельный корневой root логгер.
#
# Это уже чуть ближе к реальному серверному варианту Django. Django официально использует
# фильтры RequireDebugTrue, RequireDebugFalse, а при DEBUG=False ошибки
# могут уходить через AdminEmailHandler.


import os  # Импортируем os для чтения переменных окружения.
from pathlib import Path  # Импортируем Path для удобной сборки путей.

BASE_DIR = Path(__file__).resolve().parent.parent  # Определяем корень проекта.
LOGS_DIR = BASE_DIR / "logs"  # Папка для файлов логов.
LOGS_DIR.mkdir(exist_ok=True)  # Создаём папку логов, если она отсутствует.

DJANGO_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO")  # Позволяем задавать уровень логов Django через переменную окружения.
APP_LOG_LEVEL = os.getenv("APP_LOG_LEVEL", "DEBUG")  # Позволяем отдельно задавать уровень логов приложения через окружение.
DB_LOG_LEVEL = os.getenv("DB_LOG_LEVEL", "DEBUG" if DEBUG else "INFO")  # Для SQL-логов: в DEBUG обычно хотим DEBUG, в prod чаще приглушаем до INFO.

ADMINS = [("Admin", "admin@example.com")]  # Список администраторов, которым Django может слать письма об ошибках при DEBUG=False.

LOGGING = {  # Главный словарь конфигурации logging для Django и Python logging.
    "version": 1,  # Обязательная версия формата dictConfig для стандартного Python logging.
    "disable_existing_loggers": False,  # Не отключаем существующие логгеры Django, чтобы не потерять встроенные системные логи.
    "filters": {  # Блок фильтров, которые решают, пускать запись дальше или нет.
        "require_debug_true": {  # Фильтр, который пропускает записи только когда DEBUG=True.
            "()": "django.utils.log.RequireDebugTrue",  # Встроенный фильтр Django для dev-режима.
        },
        "require_debug_false": {  # Фильтр, который пропускает записи только когда DEBUG=False.
            "()": "django.utils.log.RequireDebugFalse",  # Встроенный фильтр Django для production-режима.
        },
    },
    "formatters": {  # Блок форматтеров: описывает, как будет выглядеть каждая строка лога.
        "console": {  # Форматтер для консольного вывода.
            "format": "[{levelname}] {asctime} {name}: {message}",  # Лаконичный формат: уровень, время, логгер и текст сообщения.
            "style": "{",  # Говорим logging, что используем форматирование в стиле str.format через фигурные скобки.
        },
        "verbose": {  # Подробный форматтер для app.log и errors.log.
            "format": "[{levelname}] {asctime} {name} | module={module} | func={funcName} | line={lineno:d} | pid={process:d} | tid={thread:d} | {message}",  # Даём максимум технического контекста для расследования проблем.
            "style": "{",  # Используем тот же стиль форматирования через фигурные скобки.
        },
        "db_verbose": {  # Отдельный форматтер специально для SQL-логов в db.log.
            "format": "[{levelname}] {asctime} {name} | module={module} | func={funcName} | line={lineno:d} | {message}",  # Для SQL нам важны время, логгер, место вызова и сам SQL-текст.
            "style": "{",  # Используем единый стиль форматирования через фигурные скобки.
        },
    },
    "handlers": {  # Блок handlers: описывает, куда физически писать лог-записи.
        "console": {  # Handler для вывода логов в терминал.
            "class": "logging.StreamHandler",  # Стандартный Python handler для stdout/stderr.
            "formatter": "console",  # Для консоли используем короткий читаемый формат.
            "filters": ["require_debug_true"],  # Консольный вывод оставляем только для DEBUG=True, чтобы prod не шумел в stdout без нужды.
            "level": "DEBUG",  # В dev-режиме хотим видеть максимум информации в консоли.
        },
        "app_file": {  # Handler для основного файла приложения.
            "class": "concurrent_log_handler.ConcurrentTimedRotatingFileHandler",  # Используем ротацию по времени, чтобы файл обновлялся регулярно.
            "filename": LOGS_DIR / "app.log",  # Путь к файлу app.log, куда пойдут общие рабочие события.
            "when": "midnight",  # Ротируем файл каждый день в полночь.
            "interval": 1,  # Интервал ротации — каждый 1 день.
            "backupCount": 14,  # Храним 14 старых файлов, чтобы иметь двухнедельную историю.
            "formatter": "verbose",  # Пишем в app.log подробный формат с большим количеством контекста.
            "level": "INFO",  # В app.log сохраняем события уровня INFO и выше.
            "encoding": "utf-8",  # Используем UTF-8, чтобы кириллица и Unicode писались корректно.
        },
        "error_file": {  # Handler для отдельного файла ошибок.
            "class": "concurrent_log_handler.ConcurrentTimedRotatingFileHandler",  # Используем ротацию по времени и для ошибок.
            "filename": LOGS_DIR / "errors.log",  # Путь к файлу, куда будут записываться только ошибки.
            "when": "midnight",  # Ротируем файл ошибок ежедневно в полночь.
            "interval": 1,  # Интервал ротации — 1 день.
            "backupCount": 30,  # Храним 30 старых файлов ошибок для более длинной истории инцидентов.
            "formatter": "verbose",  # Для ошибок используем максимально подробный формат.
            "level": "ERROR",  # В этот файл попадут только ERROR и CRITICAL.
            "encoding": "utf-8",  # Используем UTF-8 для корректной записи текста.
        },
        "db_file": {  # Handler для отдельного SQL-лога.
            "class": "concurrent_log_handler.ConcurrentTimedRotatingFileHandler",  # Используем ротацию по времени и для SQL-файла.
            "filename": LOGS_DIR / "db.log",  # Путь к db.log, куда будем писать SQL-запросы Django ORM.
            "when": "midnight",  # Ротируем db.log каждый день в полночь.
            "interval": 1,  # Интервал ротации — 1 день.
            "backupCount": 7,  # Храним 7 старых SQL-файлов, чтобы не раздувать место на диске слишком сильно.
            "formatter": "db_verbose",  # Для SQL используем отдельный форматтер, заточенный под запросы к БД.
            "level": "DEBUG",  # Чтобы SQL реально попадал в db.log, handler должен принимать DEBUG-записи.
            "encoding": "utf-8",  # Используем UTF-8 для безопасной записи текста SQL и параметров.
        },
        "mail_admins": {  # Handler для отправки ошибок на почту администраторам.
            "class": "django.utils.log.AdminEmailHandler",  # Встроенный Django handler для email-уведомлений об ошибках.
            "level": "ERROR",  # Отправляем на email только ошибки уровня ERROR и выше.
            "filters": ["require_debug_false"],  # Включаем email только при DEBUG=False, то есть в production.
        },
    },
    "root": {  # Корневой логгер Python logging на случай логгеров, которые явно не описаны ниже.
        "handlers": ["app_file", "error_file"],  # Всё непойманное хотя бы попадёт в app.log и ошибки — в errors.log.
        "level": "INFO",  # Базовый уровень для корневого логгера.
    },
    "loggers": {  # Блок именованных логгеров, которыми реально пользуются Django и приложение.
        "django": {  # Главный системный логгер Django.
            "handlers": ["console", "app_file", "error_file"],  # Пишем системные события в консоль, общий файл, файл ошибок и на почту.
            "level": DJANGO_LOG_LEVEL,  # Уровень логирования Django управляется через переменную окружения.
            "propagate": False,  # Не всплываем в root, чтобы не получить дубли одних и тех же записей.
        },
        "django.request": {  # Логгер HTTP-запросов, исключений request/response цикла и связанных ошибок.
            "handlers": ["app_file", "error_file"],  # Пишем запросные проблемы в общий файл, файл ошибок и на email.
            "level": "WARNING",  # Нас интересуют как минимум WARNING, ERROR и CRITICAL.
            "propagate": False,  # Отключаем всплытие вверх ради отсутствия дублей.
        },
        "django.server": {  # Логгер встроенного dev-сервера Django.
            "handlers": ["console"],  # Сообщения встроенного сервера достаточно видеть только в консоли.
            "level": "INFO",  # INFO хватает для стандартной картины работы dev-сервера.
            "propagate": False,  # Не передаём записи дальше, чтобы не дублировать их в файлах.
        },
        "django.db.backends": {  # Ключевой логгер Django, через который пишутся SQL-запросы к базе.
            "handlers": ["db_file"],  # Все SQL-записи отправляем только в отдельный db.log, не смешивая их с app.log.
            "level": DB_LOG_LEVEL,  # Уровень SQL-логирования управляется через переменную окружения; для запросов нужен DEBUG.
            "propagate": False,  # Не всплываем в root и другие логгеры, чтобы SQL не дублировался в app.log.
        },
        "library": {  # Основной логгер прикладного кода проекта.
            "handlers": ["console", "app_file", "error_file"],  # Логи приложения идут в консоль, общий файл, файл ошибок и на email.
            "level": APP_LOG_LEVEL,  # Уровень логов приложения можно отдельно менять через окружение.
            "propagate": False,  # Отключаем всплытие, чтобы не плодить дубликаты записей.
        },
    },
}



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
# LANGUAGE_CODE = 'uk'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
